services:
  - type: web
    name: mindscape
    env: python
    buildCommand: |
      apt-get update && apt-get install -y python3-dev build-essential
      pip install --upgrade pip
      pip install wheel
      pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: FLASK_APP
        value: wsgi.py
      - key: FLASK_ENV
        value: production 