services:
  - type: web
    name: mindscape
    env: python
    buildCommand: |
      # Install system dependencies
      apt-get update
      apt-get install -y python3-dev build-essential libpq-dev
      
      # Upgrade pip and install build tools
      python -m pip install --upgrade pip
      pip install wheel setuptools
      
      # Install Python packages
      pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: FLASK_APP
        value: wsgi.py
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "true"
    healthCheckPath: /
    autoDeploy: false 