services:
  - type: web
    name: mindscape
    env: python
    python_version: 3.9.7
    buildCommand: |
      # Install system dependencies
      apt-get update
      apt-get install -y python3-dev build-essential libpq-dev
      
      # Upgrade pip and install build tools
      python -m pip install --upgrade pip
      pip install wheel setuptools
      
      # Install gunicorn first
      pip install gunicorn==20.1.0
      
      # Install Python packages
      pip install -r requirements.txt
    startCommand: python -m gunicorn wsgi:app
    envVars:
      - key: FLASK_APP
        value: wsgi.py
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PORT
        value: "10000"
    healthCheckPath: /
    autoDeploy: false 